### ISSUE TITLE
[Bug] Server disconnection popups but the server itself is active

### ISSUE THREAD

**Issue by amywastaken** [mirukucafe/nyankey#2]
![image](https://user-images.githubusercontent.com/80048740/152695422-e347b9e8-596d-4a6e-8814-126159ab9eaf.png)

## 💡 Summary
Popup of server disconnection

an Popup of server disconnection
## 🙂 Expected Behavior
never appear while the server is active

## ☹️ Actual Behavior
it appears after while (if you keep the tab open)

## 📝 Steps to Reproduce

1. Open miruku
2. Wait 
3. You will see it in the left bottom corner

## 📌 Environment

web - Firefox

**Comment by janderedev** [comment]
@geshii would you mind not assigning everyone to everything btw
