### ISSUE TITLE
[UI & Design] UI Improvements

### ISSUE THREAD

**Issue by initmd** [mirukucafe/nyankey#4]
- [x] Fix font
- [x] Default Dark Theme
- [x] Change color scheme according to what was discussed over the [dev Discord channel ](https://discord.gg/mirukucafe)

**Comment by infi** [comment]
[Work Sans](https://fonts.google.com/specimen/Work+Sans)
![image](https://user-images.githubusercontent.com/45950794/154819234-51ec75a9-108b-4108-8f0b-e903cbc2ec49.png)
![image](https://user-images.githubusercontent.com/45950794/154819294-11bcc2eb-d519-46c3-a1e8-830b312cccb3.png)

**Comment by initmd** [comment]
This issue will be closed in the newest release. 
Pushing on prod and committing in a few hours

**Comment by FanMclaine** [comment]
calckey
